##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-applets
    - clang
    - cpupower
    - gcc
    - git
    - gucharmap
    - gtksourceview3
    - itstool
    - libgtop
    - libnotify
    - make
    - mate-common
    - mate-panel
    - polkit
    - upower
    - which
    - wireless_tools
    - yelp-tools
    - autoconf-archive

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-applets
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libcpupower-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libgtop2-dev
    - libgucharmap-2-90-dev
    - libiw-dev
    - libmate-panel-applet-dev
    - libmateweather-dev
    - libnotify-dev
    - libpolkit-gobject-1-dev
    - libupower-glib-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - x11proto-kb-dev
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-applets.git
    - clang
    - clang-analyzer
    - cppcheck-htmlreport
    - gcc
    - git
    - gtksourceview3-devel
    - gucharmap-devel
    - kernel-tools-libs-devel
    - libgtop2-devel
    - libnotify-devel
    - libmateweather-devel
    - libwnck3-devel
    - libxml2-devel
    - libICE-devel
    - libSM-devel
    - make
    - mate-common
    - mate-settings-daemon-devel
    - mate-notification-daemon
    - mate-panel-devel
    - polkit-devel
    - redhat-rpm-config
    - startup-notification-devel
    - upower-devel
    - wireless-tools-devel

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - libcpufreq-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libgtop2-dev
    - libgucharmap-2-90-dev
    - libiw-dev
    - libmate-panel-applet-dev
    - libmateweather-dev
    - libnotify-dev
    - libpolkit-gobject-1-dev
    - libupower-glib-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - x11proto-kb-dev
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security -Wextra -Wchar-subscripts -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wcast-align -Wunused-but-set-variable -Wformat-nonliteral -Wabsolute-value -Wredundant-decls"
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
  - ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-applets/raw/master/cpufreq/pixmaps/cpufreq-100.png
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-applets-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

